### ISSUE TITLE
Modernise layout

### ISSUE THREAD

**Issue by CJKerr** [powderworks/powderworks.github.io#4]
At the moment, much of the page layout is handled in a fairly old-fashioned way that conflicts with the more semantic design of the modern web.

For instance, page layout is handled by a table, rather than using the box model or flexbox, we're using text attributes to center an image, breaks rather than padding for vertical alignment, etc, etc.

In the interests of accessibility (and to permit easier adaptation to alternative layouts e.g. mobile) I'd like to take a first pass at modernising the page structure, without changing its actual (desktop-size) layout. Any objections?

**Comment by robmanthey** [comment]
Yep. Totally agree. The original site was just a concept layout to show the idea we are after.

**Comment by CJKerr** [comment]
In my opinion this issue can be closed - PR #6 addresses my original point, and anything more specific should probably get a new issue.
